language: node_js
node_js:
- '11'
- '10'
- '8'

services:
  - docker

env:
  global:
    secure: MyuCEVSZN9q21xgU/iF4TnKD1WMYohEWxtVI+nOu92A0HDYk3kyu3HanocXwbDLW1AJOL61VK+VkxOsZt773dG5yZ7LyD5fbwtlPu8Q4OTvtQ2+HwCtHIlxobDQg3KdPE55rw0BVYgbJzsppDd9DuPcPNYvbkndcA4d9D6HpfBr8lfE0fjswB+jtmHUSeCcXfEym3wUc8JogZYAlolZjOwX65owr2YCxbWeVJKqWM+N/XkpQrRTf4F0hdaVovBxsMQqLbH0J1Rk2mG4qKiIJMdt5xrtnjhf+SLJPZG+abRTwlz7DC7rlQOFVE1cvL3LLdNy7uvlUOSpU5xg2BpLMxlhJBUZm4SDBEq1dwbVd4fVhnd2rzP7OWM5ZHcMd+XDQqCLR8qzy7lSmGI+6hslGcnM9nydBxGBOTPoMRDgSj0sCn3WTJaUc/SIvRyHKsFzFzZGeChi9idr+TSRAZTwTPNxzsSU+cIxsDXQIbm8tVYNPILioQfp72c8Dd5r6pV53M7UQbrt/COo6Hc2Kexe1Lx3xvU+Thmq3zyPQPJ7c14d09E03mzxrCtEj2WCeioD261ubxMAa97KYIuKF99efMIx8e6OhcFmXG6wnBtFI2rTYbmzNrTpTlPQEN0+gay7TxoybmDdkE+uwCyYUcPJVuYL+0xXQcR0L8mwyKiGACQk=

before_script:
  - docker run -d -p 9200:9200 -e discovery.type=single-node docker.elastic.co/elasticsearch/elasticsearch:6.5.4
  - sleep 20

script:
  - yarn test:integration
  - yarn coverage

after_success: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN} -f coverage/lcov.info

deploy:
  provider: npm
  email: warchantua@gmail.com
  api_key:
    secure: woDTbB6usSbxATH0GEJLl9b83pxPJGisjLWZhpAxkMsl81rrGEWroHsyj9EPchj9zGXsTIaicPAE7eSg+Cl2Q59cG/3r64AlJWFigfoAThtauh5S6nK4zRd4o1diz3yk0rnDoJWQC/Vz65aCelq1KcPVPB3OXEFs5AtTA59Gnf7QWMG4iVeKqPC6ZA9D08AVHMJ+ki687SncoNw6oH/EKr4rjxXvOAoaLBKciTzpuSksAD0qvkBhqjUWw2XYf7/vynrWpEB/6ZF3lNKqlLuWXtsk7pcpitJ4tiqYH41nyel9EBRmd4mJWH4I9cQemGP3J/0dizrUoeUTsDeacIhcZqx2w0ZI02irYVlTm5N7WpzzyI+8E/oBBbO/R4gRhDC4xa26LGa6YYsx9k+6D+XvxY3liDLnzJp193iE+kQyt4UMOUnXJU+kqH5MbG+5mJiXN4JbC13cEVKZlRpLRPQmEfkZ1BaKLE5DNt0tYjDFvzIe9qYBKNgi9yKh5XVFa6nEQpN97DTaWt7rHso57Mxc2vLK6yaaxJXi0Fqsw3Nrka4uMMkQVYidd2jDugjfV2RUQ/czBbRchU+Fq5KswTZwmYlFmSSRvjHF6fKr5AQyLuFH4odCStfLODl8l8NPJ5t0Lc+ab/UyXsd4wzuoHySvos5uL8ud0tvLcxCI34CK42A=
  on:
    tags: true
    repo: Warchant/node-ts-elasticsearch
